### ISSUE TITLE
enable `size-adjust` metric calculation

### ISSUE THREAD

**Issue by danielroe** [danielroe/fontaine#8]
Currently we can use metrics to adjust vertical height accurately. There's still a horizontal mismatch though, even if slight, and we can likely solve this by applying the right metrics to `size-adjust`.

**Comment by Kevin-Hamilton** [comment]
I think you can _improve_ the horizontal mismatch, but not _solve_ it.  

Looking at the "On Font Width..." section at the bottom of this [notes on calculating font metric overrides](https://docs.google.com/document/d/e/2PACX-1vRsazeNirATC7lIj2aErSHpK26hZ6dA9GsQ069GEbq5fyzXEhXbvByoftSfhG82aJXmrQ_sJCPBqcx_/pub) document, because the width of each character contributes a different amount to the width of the line, the `size-adjust` width adjustment can only be calculated accurately if you know the specific set of characters it will apply to.

In [this example](https://overrides-and-size-adjust-demo.glitch.me/), you can see how size-adjust can make the fallback font match up exactly for the configured text value, "abcdefghijklmnopqrstuvwxyz":
![image](https://user-images.githubusercontent.com/508865/196326729-0147de48-eca2-46ad-a797-8a7b3e817dcc.png)

But for different text content, that size adjustment will no longer match so perfectly:
![image](https://user-images.githubusercontent.com/508865/196326873-8b18da3a-1aaf-416e-a667-a21df91ce1c9.png)

**Comment by danielroe** [comment]
That is correct. As the document says:

> Quantifying width has many potential variations: for example, weighting by character frequency, weighing some characters more heavily (e.g. narrow/wide characters like “i,j,m,w”), taking the average width of all glyphs (i.e. not just “abc...z”), etc. Some of these “fancier” approaches might not generalize well across languages.

**Comment by slorber** [comment]
As far as I understand Next 13 just implemented this too 😄 https://twitter.com/Una/status/1584967596847542272

**Comment by johnnyreilly** [comment]
This is fundamentally an awesome idea. My bet is that in the long run, what fontaine and Next are doing becomes native browser functionality in some way

**Comment by LogansDad** [comment]
FYI - For anyone who cares about CLS on mobile, `size-adjust` does not work on Chrome for Android
https://bugs.chromium.org/p/chromium/issues/detail?id=1370818

**Comment by AleksandrHovhannisyan** [comment]
I use Malte Ubl's tool here to get my size-adjust calculations: https://www.industrialempathy.com/perfect-ish-font-fallback/. Source code here: https://www.industrialempathy.com/perfect-ish-font-fallback/font.js?hash=69bb1d4305. I admittedly don't follow the logic for `resizeText`, but it works wonderfully. I wonder if there's a way to use the existing font metrics from `capsize` to compute something similar.

[MDN says](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/size-adjust):

> The size-adjust descriptor behaves in a similar fashion to the [font-size-adjust](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust) property. It calculates an adjustment per font by matching ex heights.

But it's unclear what "matching ex heights" means in terms of the computations.

**Comment by LogansDad** [comment]
BTW, @danielroe, I started using `size-adjust` recently on Chrome for Android and it now works. BTW, Android does not have many common web fonts, so the comparison from one custom font to a fallback font will only work if the fallback font is `Roboto` or `Noto Serif`

http://fontfamily.io/

**Comment by danielroe** [comment]
implemented in #181!
